#pragma once
#include <SFML/Graphics.hpp>
#include "GameData.hpp"
#include <string>
#include <vector>
#include <array>
#include <optional>

void drawBoardAndUI(
    sf::RenderWindow& window,
    sf::RectangleShape& tile,
    sf::Color& lightColor,
    sf::Color& darkColor,
    sf::Color& checkedKingTileColor,
    std::optional<sf::Vector2i>& selectedPiecePos,
    std::vector<sf::Vector2i>& possibleMoves,
    sf::Text& whiteTimerText,
    sf::Text& blackTimerText,
    sf::Text& messageText,
    std::string& gameMessageStr,
    sf::Text& popupMessageText,
    sf::Sprite& popupImageSprite,
    sf::Sprite& homeButtonSprite,
    GameState& currentGameState,
    PieceColor& currentTurn,
    sf::Vector2i checkedKingCurrentPos,
    std::array<std::array<std::optional<Piece>, 8>, 8>& board_state,
    sf::Sprite& startButtonSprite,
    sf::RectangleShape& blackStartButton,
    sf::Text& blackStartText,
    sf::Sprite& backgroundSprite,
    sf::Sprite& logoSprite,
    sf::Sprite& uiPanelBgSprite,
    sf::Sprite& player1Sprite,
    sf::Sprite& player2Sprite,
    sf::Text& player1NameText,
    sf::Text& player2NameText,
    sf::Texture& player1Texture,
    sf::Texture& player2Texture,
    sf::Texture& waitingTexture
);
